# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        include:
          - { os: windows-latest, cc: cl, cxx: cl }
          - { os: ubuntu-latest, cc: gcc, cxx: g++ }
          - { os: ubuntu-latest, cc: clang, cxx: clang++ }

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
        CMAKE_BUILD_TYPE: Debug
        CTEST_OUTPUT_ON_FAILURE: "1"
      run: cmake --preset default

    - name: Build
      run: cmake --build --preset default

    - name: Test
      run: ctest --preset default
